package com.example.farmer.navigation

const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_HOMESCREEN = "homescreen"
const val ROUTE_START = "start"
const val ROUTE_SETTINGS = "settings/ProfileScreen"
const val ROUTE_SPLASH = "splash"
const val ROUTE_WEATHER = "weather"
const val ROUTE_POST = "tips/PostTipsScreen"
const val ROUTE_TIPS = "tips/FeedScreen"
const val ROUTE_CROPFEED = "crops/CropFeedScreen"
const val ROUTE_CROPFORM ="crops/CropsScreen"
const val ROUTE_PASSWORD = "password?ChangePassword"
const val ROUTE_CHANGEDPASSWORD = "password/PasswordChanged"